const EXERCISES_ROUTE = 'EXERCISES_ROUTE'
const EXERCISE_DETAILS_ROUTE = 'EXERCISE_DETAILS_ROUTE'
const ROUTINES_ROUTE = 'ROUTINES_ROUTE'
const ROUTINE_DETAILS_ROUTE = 'ROUTINE_DETAILS_ROUTE'

export {
  EXERCISES_ROUTE,
  ROUTINES_ROUTE,
  EXERCISE_DETAILS_ROUTE,
  ROUTINE_DETAILS_ROUTE
}
